trigger:
  - master

jobs:
- job: Windows
  timeoutInMinutes: 0

  pool:
    vmImage: windows-2019

  steps:
  - script: |
      set /p TEMP-SHA=<llvm-sha.txt
      echo %TEMP-SHA%
      "C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe"
      echo %TEMP-SHA%
      Write-Host "##vso[task.setvariable variable=LLVM-SHA;]%TEMP-SHA%"
    displayName: 'Read commit SHA'

  - publish: $(System.DefaultWorkingDirectory)/llvm-sha.txt
    artifact: 'mlir-llvm_$(LLVM-SHA)_$(Agent.OS)'
    displayName: 'Publish artifact'
