trigger:
- master

timeoutInMinutes: 0

pool:
  vmImage: windows-2019

steps:

  - script: |
    call cmake --version
    set /p llvm-sha=<llvm-sha.txt
    call pip install ninja
    git clone https://github.com/llvm/llvm-project.git
    cd llvm-project
    git checkout %llvm-sha%
    cmake ..\llvm-project\llvm -G "Ninja" -DLLVM_ENABLE_PROJECTS=mlir -DLLVM_BUILD_EXAMPLES=ON -DLLVM_TARGETS_TO_BUILD="host" -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=ON -DCMAKE_INSTALL_PREFIX=..\mlir-llvm
    ninja install
    displayName: 'Build'

  - publish: $(System.DefaultWorkingDirectory)/mlir-llvm
    artifact: 'mlir-llvm_latest_$(Agent.OS)'
    displayName: 'Publish artifact'
