trigger:
  - master

jobs:
- job: Windows
  timeoutInMinutes: 0

  pool:
    vmImage: windows-2019

  steps:
  - script: |
      set /p TEMP-SHA=<llvm-sha.txt
      echo %TEMP-SHA%
    displayName: 'Read commit SHA'

  - task: PowerShell@2
    displayName: 'Set commit SHA'
    inputs:
      targetType: 'inline'
      script: |
        echo %TEMP-SHA%
        Write-Host "##vso[task.setvariable variable=LLVM-SHA;]%TEMP-SHA%"

  - publish: $(System.DefaultWorkingDirectory)/llvm-sha.txt
    artifact: 'mlir-llvm_$(LLVM-SHA)_$(Agent.OS)'
    displayName: 'Publish artifact'
