trigger:
  - master

jobs:
- job: Windows
  timeoutInMinutes: 0

  pool:
    vmImage: windows-2019

  steps:
  - script: |
      set /p TEMPSHA=<llvm-sha.txt
      echo %TEMPSHA%
      echo ##vso[task.setvariable variable=LLVMSHA;]shasha
      echo $(LLVMSHA)
    displayName: 'Read commit SHA'

  - publish: $(System.DefaultWorkingDirectory)/llvm-sha.txt
    artifact: 'mlir-llvm_$(LLVMSHA)_$(Agent.OS)'
    displayName: 'Publish artifact'
