trigger:
  - master

jobs:
- job: Windows
  timeoutInMinutes: 0
  
  variables:
    TEMP-SHA: 'empty'
    LLVM-SHA: 'empty'

  pool:
    vmImage: windows-2019

  steps:
  - task: PowerShell@2
    displayName: 'Set commit SHA'
    inputs:
      targetType: 'inline'
      script: |
        set /p TEMP-SHA=<llvm-sha.txt
        Write-Host "##vso[task.setvariable variable=LLVM-SHA;]$[variables.TEMP-SHA]"

  - publish: $(System.DefaultWorkingDirectory)/llvm-sha.txt
    artifact: 'mlir-llvm_$(LLVM-SHA)_$(Agent.OS)'
    displayName: 'Publish artifact'
